"""add lineup field simulation metrics

Revision ID: 0cbb7534f418
Revises: 4c5be19aaea1
Create Date: 2026-09-15 04:27:18.391134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cbb7534f418'
down_revision: Union[str, None] = '4c5be19aaea1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lineups', sa.Column('sim_win_pct', sa.Float(), nullable=True))
    op.add_column('lineups', sa.Column('sim_top1pct_pct', sa.Float(), nullable=True))
    op.add_column('lineups', sa.Column('sim_cash_pct', sa.Float(), nullable=True))
    op.add_column('lineups', sa.Column('sim_roi_pct', sa.Float(), nullable=True))
    op.add_column('lineups', sa.Column('sim_payout_basis', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lineups', 'sim_payout_basis')
    op.drop_column('lineups', 'sim_roi_pct')
    op.drop_column('lineups', 'sim_cash_pct')
    op.drop_column('lineups', 'sim_top1pct_pct')
    op.drop_column('lineups', 'sim_win_pct')
    # ### end Alembic commands ###
