"""add dk draftable id fields

Revision ID: 4c5be19aaea1
Revises: 4cfbb4142e7c
Create Date: 2026-09-14 20:45:04.508559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c5be19aaea1'
down_revision: Union[str, None] = '4cfbb4142e7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('draftkings_players', sa.Column('dk_draftable_id', sa.String(length=32), nullable=True))
    op.add_column('draftkings_players', sa.Column('dk_captain_draftable_id', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('draftkings_players', 'dk_captain_draftable_id')
    op.drop_column('draftkings_players', 'dk_draftable_id')
    # ### end Alembic commands ###
