"""add slate injury_alert_detail

Revision ID: 4cfbb4142e7c
Revises: ba409e076316
Create Date: 2026-09-14 19:30:55.074961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cfbb4142e7c'
down_revision: Union[str, None] = 'ba409e076316'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slates', sa.Column('injury_alert_detail', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slates', 'injury_alert_detail')
    # ### end Alembic commands ###
