"""initial schema

Revision ID: 76ff3de81e3e
Revises: 
Create Date: 2026-09-12 19:29:56.583369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76ff3de81e3e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_versions',
    sa.Column('sport', sa.String(length=16), nullable=False),
    sa.Column('version_tag', sa.String(length=32), nullable=False),
    sa.Column('component', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('config_snapshot', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_versions_sport'), 'model_versions', ['sport'], unique=False)
    op.create_table('projection_sources',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('default_confidence', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('slates',
    sa.Column('sport', sa.String(length=16), nullable=False),
    sa.Column('contest_type', sa.String(length=16), nullable=False),
    sa.Column('dk_draft_group_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('start_time_utc', sa.DateTime(), nullable=False),
    sa.Column('game_ids', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slates_dk_draft_group_id'), 'slates', ['dk_draft_group_id'], unique=True)
    op.create_index(op.f('ix_slates_sport'), 'slates', ['sport'], unique=False)
    op.create_table('teams',
    sa.Column('sport', sa.String(length=16), nullable=False),
    sa.Column('abbreviation', sa.String(length=8), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('external_ids', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_abbreviation'), 'teams', ['abbreviation'], unique=False)
    op.create_index(op.f('ix_teams_sport'), 'teams', ['sport'], unique=False)
    op.create_table('contests',
    sa.Column('slate_id', sa.String(length=36), nullable=False),
    sa.Column('dk_contest_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('contest_type', sa.String(length=16), nullable=False),
    sa.Column('entry_fee', sa.Float(), nullable=False),
    sa.Column('total_prizes', sa.Float(), nullable=False),
    sa.Column('max_entries', sa.Integer(), nullable=False),
    sa.Column('max_entries_per_user', sa.Integer(), nullable=False),
    sa.Column('entries', sa.Integer(), nullable=False),
    sa.Column('payout_structure', sa.JSON(), nullable=False),
    sa.Column('is_guaranteed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['slate_id'], ['slates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contests_dk_contest_id'), 'contests', ['dk_contest_id'], unique=True)
    op.create_index(op.f('ix_contests_slate_id'), 'contests', ['slate_id'], unique=False)
    op.create_table('games',
    sa.Column('sport', sa.String(length=16), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('home_team_id', sa.String(length=36), nullable=False),
    sa.Column('away_team_id', sa.String(length=36), nullable=False),
    sa.Column('kickoff_utc', sa.DateTime(), nullable=False),
    sa.Column('venue', sa.String(length=128), nullable=True),
    sa.Column('is_dome', sa.Boolean(), nullable=False),
    sa.Column('external_ids', sa.JSON(), nullable=False),
    sa.Column('home_score_final', sa.Integer(), nullable=True),
    sa.Column('away_score_final', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_away_team_id'), 'games', ['away_team_id'], unique=False)
    op.create_index(op.f('ix_games_home_team_id'), 'games', ['home_team_id'], unique=False)
    op.create_index(op.f('ix_games_kickoff_utc'), 'games', ['kickoff_utc'], unique=False)
    op.create_index(op.f('ix_games_season'), 'games', ['season'], unique=False)
    op.create_index(op.f('ix_games_sport'), 'games', ['sport'], unique=False)
    op.create_index(op.f('ix_games_week'), 'games', ['week'], unique=False)
    op.create_table('players',
    sa.Column('sport', sa.String(length=16), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('normalized_name', sa.String(length=128), nullable=False),
    sa.Column('position', sa.String(length=8), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('external_ids', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_full_name'), 'players', ['full_name'], unique=False)
    op.create_index(op.f('ix_players_normalized_name'), 'players', ['normalized_name'], unique=False)
    op.create_index(op.f('ix_players_position'), 'players', ['position'], unique=False)
    op.create_index(op.f('ix_players_sport'), 'players', ['sport'], unique=False)
    op.create_index(op.f('ix_players_team_id'), 'players', ['team_id'], unique=False)
    op.create_table('simulations',
    sa.Column('slate_id', sa.String(length=36), nullable=False),
    sa.Column('model_version_id', sa.String(length=36), nullable=True),
    sa.Column('num_simulations', sa.Integer(), nullable=False),
    sa.Column('random_seed', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['slate_id'], ['slates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulations_slate_id'), 'simulations', ['slate_id'], unique=False)
    op.create_table('betting_lines',
    sa.Column('game_id', sa.String(length=36), nullable=False),
    sa.Column('book', sa.String(length=64), nullable=False),
    sa.Column('spread_home', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('moneyline_home', sa.Integer(), nullable=True),
    sa.Column('moneyline_away', sa.Integer(), nullable=True),
    sa.Column('implied_total_home', sa.Float(), nullable=True),
    sa.Column('implied_total_away', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_betting_lines_game_id'), 'betting_lines', ['game_id'], unique=False)
    op.create_table('correlations',
    sa.Column('slate_id', sa.String(length=36), nullable=False),
    sa.Column('player_a_id', sa.String(length=36), nullable=False),
    sa.Column('player_b_id', sa.String(length=36), nullable=False),
    sa.Column('relationship_type', sa.String(length=32), nullable=False),
    sa.Column('correlation', sa.Float(), nullable=False),
    sa.Column('is_empirical', sa.Boolean(), nullable=False),
    sa.Column('sample_games', sa.Integer(), nullable=False),
    sa.Column('condition', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_a_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['player_b_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['slate_id'], ['slates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_correlations_player_a_id'), 'correlations', ['player_a_id'], unique=False)
    op.create_index(op.f('ix_correlations_player_b_id'), 'correlations', ['player_b_id'], unique=False)
    op.create_index(op.f('ix_correlations_slate_id'), 'correlations', ['slate_id'], unique=False)
    op.create_table('draftkings_players',
    sa.Column('slate_id', sa.String(length=36), nullable=False),
    sa.Column('player_id', sa.String(length=36), nullable=True),
    sa.Column('dk_player_id', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('dk_position', sa.String(length=8), nullable=False),
    sa.Column('team_abbreviation', sa.String(length=8), nullable=False),
    sa.Column('opponent_abbreviation', sa.String(length=8), nullable=False),
    sa.Column('game_id', sa.String(length=36), nullable=True),
    sa.Column('roster_status', sa.String(length=32), nullable=False),
    sa.Column('is_starting', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['slate_id'], ['slates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_draftkings_players_dk_player_id'), 'draftkings_players', ['dk_player_id'], unique=False)
    op.create_index(op.f('ix_draftkings_players_player_id'), 'draftkings_players', ['player_id'], unique=False)
    op.create_index(op.f('ix_draftkings_players_slate_id'), 'draftkings_players', ['slate_id'], unique=False)
    op.create_table('ensemble_projections',
    sa.Column('slate_id', sa.String(length=36), nullable=False),
    sa.Column('player_id', sa.String(length=36), nullable=False),
    sa.Column('model_version_id', sa.String(length=36), nullable=False),
    sa.Column('source_projection_1', sa.Float(), nullable=True),
    sa.Column('source_projection_2', sa.Float(), nullable=True),
    sa.Column('source_projection_3', sa.Float(), nullable=True),
    sa.Column('market_projection', sa.Float(), nullable=True),
    sa.Column('model_projection', sa.Float(), nullable=True),
    sa.Column('ensemble_projection', sa.Float(), nullable=False),
    sa.Column('floor', sa.Float(), nullable=False),
    sa.Column('median', sa.Float(), nullable=False),
    sa.Column('ceiling', sa.Float(), nullable=False),
    sa.Column('std_dev', sa.Float(), nullable=False),
    sa.Column('weights_used', sa.JSON(), nullable=False),
    sa.Column('component_breakdown', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['slate_id'], ['slates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ensemble_projections_player_id'), 'ensemble_projections', ['player_id'], unique=False)
    op.create_index(op.f('ix_ensemble_projections_slate_id'), 'ensemble_projections', ['slate_id'], unique=False)
    op.create_table('optimization_runs',
    sa.Column('slate_id', sa.String(length=36), nullable=False),
    sa.Column('simulation_run_id', sa.String(length=36), nullable=True),
    sa.Column('objective', sa.String(length=32), nullable=False),
    sa.Column('num_lineups_requested', sa.Integer(), nullable=False),
    sa.Column('num_lineups_generated', sa.Integer(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['simulation_run_id'], ['simulations.id'], ),
    sa.ForeignKeyConstraint(['slate_id'], ['slates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimization_runs_slate_id'), 'optimization_runs', ['slate_id'], unique=False)
    op.create_table('ownership_projections',
    sa.Column('slate_id', sa.String(length=36), nullable=False),
    sa.Column('player_id', sa.String(length=36), nullable=False),
    sa.Column('projected_ownership_pct', sa.Float(), nullable=False),
    sa.Column('optimal_ownership_pct', sa.Float(), nullable=True),
    sa.Column('leverage', sa.Float(), nullable=True),
    sa.Column('chalk_score', sa.Float(), nullable=True),
    sa.Column('contrarian_score', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('feature_breakdown', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['slate_id'], ['slates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ownership_projections_player_id'), 'ownership_projections', ['player_id'], unique=False)
    op.create_index(op.f('ix_ownership_projections_slate_id'), 'ownership_projections', ['slate_id'], unique=False)
    op.create_table('player_injuries',
    sa.Column('player_id', sa.String(length=36), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('practice_status', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('reported_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_injuries_player_id'), 'player_injuries', ['player_id'], unique=False)
    op.create_table('player_news',
    sa.Column('player_id', sa.String(length=36), nullable=False),
    sa.Column('headline', sa.String(length=512), nullable=False),
    sa.Column('body', sa.String(length=4096), nullable=True),
    sa.Column('impact', sa.String(length=16), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_news_player_id'), 'player_news', ['player_id'], unique=False)
    op.create_table('player_simulation_results',
    sa.Column('simulation_run_id', sa.String(length=36), nullable=False),
    sa.Column('player_id', sa.String(length=36), nullable=False),
    sa.Column('mean', sa.Float(), nullable=False),
    sa.Column('median', sa.Float(), nullable=False),
    sa.Column('std_dev', sa.Float(), nullable=False),
    sa.Column('floor', sa.Float(), nullable=False),
    sa.Column('ceiling', sa.Float(), nullable=False),
    sa.Column('percentiles', sa.JSON(), nullable=False),
    sa.Column('prob_3x_salary', sa.Float(), nullable=False),
    sa.Column('prob_4x_salary', sa.Float(), nullable=False),
    sa.Column('prob_5x_salary', sa.Float(), nullable=False),
    sa.Column('prob_6x_salary', sa.Float(), nullable=False),
    sa.Column('prob_top1pct', sa.Float(), nullable=False),
    sa.Column('prob_top5pct', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['simulation_run_id'], ['simulations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_simulation_results_player_id'), 'player_simulation_results', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_simulation_results_simulation_run_id'), 'player_simulation_results', ['simulation_run_id'], unique=False)
    op.create_table('player_snapshots',
    sa.Column('player_id', sa.String(length=36), nullable=False),
    sa.Column('as_of', sa.DateTime(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('games_sampled', sa.Integer(), nullable=False),
    sa.Column('usage', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_snapshots_as_of'), 'player_snapshots', ['as_of'], unique=False)
    op.create_index(op.f('ix_player_snapshots_player_id'), 'player_snapshots', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_snapshots_season'), 'player_snapshots', ['season'], unique=False)
    op.create_index(op.f('ix_player_snapshots_week'), 'player_snapshots', ['week'], unique=False)
    op.create_table('player_stats',
    sa.Column('player_id', sa.String(length=36), nullable=False),
    sa.Column('game_id', sa.String(length=36), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('dk_fantasy_points', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_stats_game_id'), 'player_stats', ['game_id'], unique=False)
    op.create_index(op.f('ix_player_stats_player_id'), 'player_stats', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_stats_season'), 'player_stats', ['season'], unique=False)
    op.create_index(op.f('ix_player_stats_week'), 'player_stats', ['week'], unique=False)
    op.create_table('weather',
    sa.Column('game_id', sa.String(length=36), nullable=False),
    sa.Column('temperature_f', sa.Float(), nullable=True),
    sa.Column('wind_mph', sa.Float(), nullable=True),
    sa.Column('wind_direction_deg', sa.Float(), nullable=True),
    sa.Column('precipitation_pct', sa.Float(), nullable=True),
    sa.Column('precipitation_type', sa.String(length=16), nullable=True),
    sa.Column('humidity_pct', sa.Float(), nullable=True),
    sa.Column('is_forecast', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_game_id'), 'weather', ['game_id'], unique=False)
    op.create_table('draftkings_salaries',
    sa.Column('dk_player_id_fk', sa.String(length=36), nullable=False),
    sa.Column('salary', sa.Integer(), nullable=False),
    sa.Column('effective_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dk_player_id_fk'], ['draftkings_players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_draftkings_salaries_dk_player_id_fk'), 'draftkings_salaries', ['dk_player_id_fk'], unique=False)
    op.create_table('lineups',
    sa.Column('optimization_run_id', sa.String(length=36), nullable=False),
    sa.Column('slate_id', sa.String(length=36), nullable=False),
    sa.Column('salary_used', sa.Integer(), nullable=False),
    sa.Column('salary_remaining', sa.Integer(), nullable=False),
    sa.Column('projected_points', sa.Float(), nullable=False),
    sa.Column('ceiling', sa.Float(), nullable=False),
    sa.Column('floor', sa.Float(), nullable=False),
    sa.Column('projected_ownership_product', sa.Float(), nullable=True),
    sa.Column('leverage_score', sa.Float(), nullable=True),
    sa.Column('stack_type', sa.String(length=32), nullable=True),
    sa.Column('stack_description', sa.String(length=256), nullable=True),
    sa.Column('uniqueness_score', sa.Float(), nullable=True),
    sa.Column('ai_rank', sa.Integer(), nullable=True),
    sa.Column('ai_score', sa.Float(), nullable=True),
    sa.Column('explanation', sa.String(length=2048), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['optimization_run_id'], ['optimization_runs.id'], ),
    sa.ForeignKeyConstraint(['slate_id'], ['slates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lineups_optimization_run_id'), 'lineups', ['optimization_run_id'], unique=False)
    op.create_index(op.f('ix_lineups_slate_id'), 'lineups', ['slate_id'], unique=False)
    op.create_table('projections',
    sa.Column('slate_id', sa.String(length=36), nullable=False),
    sa.Column('player_id', sa.String(length=36), nullable=False),
    sa.Column('dk_player_id_fk', sa.String(length=36), nullable=True),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('model_version_id', sa.String(length=36), nullable=True),
    sa.Column('projected_points', sa.Float(), nullable=False),
    sa.Column('floor', sa.Float(), nullable=True),
    sa.Column('median', sa.Float(), nullable=True),
    sa.Column('ceiling', sa.Float(), nullable=True),
    sa.Column('std_dev', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('inputs', sa.JSON(), nullable=False),
    sa.Column('component_breakdown', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dk_player_id_fk'], ['draftkings_players.id'], ),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['slate_id'], ['slates.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['projection_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projections_dk_player_id_fk'), 'projections', ['dk_player_id_fk'], unique=False)
    op.create_index(op.f('ix_projections_player_id'), 'projections', ['player_id'], unique=False)
    op.create_index(op.f('ix_projections_slate_id'), 'projections', ['slate_id'], unique=False)
    op.create_index(op.f('ix_projections_source_id'), 'projections', ['source_id'], unique=False)
    op.create_table('backtest_results',
    sa.Column('slate_id', sa.String(length=36), nullable=False),
    sa.Column('player_id', sa.String(length=36), nullable=False),
    sa.Column('model_version_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.String(length=8), nullable=False),
    sa.Column('salary', sa.Integer(), nullable=False),
    sa.Column('game_total', sa.Float(), nullable=True),
    sa.Column('predicted_points', sa.Float(), nullable=False),
    sa.Column('actual_points', sa.Float(), nullable=True),
    sa.Column('predicted_ownership_pct', sa.Float(), nullable=True),
    sa.Column('actual_ownership_pct', sa.Float(), nullable=True),
    sa.Column('lineup_id', sa.String(length=36), nullable=True),
    sa.Column('lineup_actual_points', sa.Float(), nullable=True),
    sa.Column('lineup_roi', sa.Float(), nullable=True),
    sa.Column('contest_percentile', sa.Float(), nullable=True),
    sa.Column('error_breakdown', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lineup_id'], ['lineups.id'], ),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['slate_id'], ['slates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_results_model_version_id'), 'backtest_results', ['model_version_id'], unique=False)
    op.create_index(op.f('ix_backtest_results_player_id'), 'backtest_results', ['player_id'], unique=False)
    op.create_index(op.f('ix_backtest_results_position'), 'backtest_results', ['position'], unique=False)
    op.create_index(op.f('ix_backtest_results_slate_id'), 'backtest_results', ['slate_id'], unique=False)
    op.create_table('lineup_players',
    sa.Column('lineup_id', sa.String(length=36), nullable=False),
    sa.Column('player_id', sa.String(length=36), nullable=False),
    sa.Column('roster_slot', sa.String(length=8), nullable=False),
    sa.Column('salary', sa.Integer(), nullable=False),
    sa.Column('projected_points', sa.Float(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lineup_id'], ['lineups.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lineup_players_lineup_id'), 'lineup_players', ['lineup_id'], unique=False)
    op.create_index(op.f('ix_lineup_players_player_id'), 'lineup_players', ['player_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lineup_players_player_id'), table_name='lineup_players')
    op.drop_index(op.f('ix_lineup_players_lineup_id'), table_name='lineup_players')
    op.drop_table('lineup_players')
    op.drop_index(op.f('ix_backtest_results_slate_id'), table_name='backtest_results')
    op.drop_index(op.f('ix_backtest_results_position'), table_name='backtest_results')
    op.drop_index(op.f('ix_backtest_results_player_id'), table_name='backtest_results')
    op.drop_index(op.f('ix_backtest_results_model_version_id'), table_name='backtest_results')
    op.drop_table('backtest_results')
    op.drop_index(op.f('ix_projections_source_id'), table_name='projections')
    op.drop_index(op.f('ix_projections_slate_id'), table_name='projections')
    op.drop_index(op.f('ix_projections_player_id'), table_name='projections')
    op.drop_index(op.f('ix_projections_dk_player_id_fk'), table_name='projections')
    op.drop_table('projections')
    op.drop_index(op.f('ix_lineups_slate_id'), table_name='lineups')
    op.drop_index(op.f('ix_lineups_optimization_run_id'), table_name='lineups')
    op.drop_table('lineups')
    op.drop_index(op.f('ix_draftkings_salaries_dk_player_id_fk'), table_name='draftkings_salaries')
    op.drop_table('draftkings_salaries')
    op.drop_index(op.f('ix_weather_game_id'), table_name='weather')
    op.drop_table('weather')
    op.drop_index(op.f('ix_player_stats_week'), table_name='player_stats')
    op.drop_index(op.f('ix_player_stats_season'), table_name='player_stats')
    op.drop_index(op.f('ix_player_stats_player_id'), table_name='player_stats')
    op.drop_index(op.f('ix_player_stats_game_id'), table_name='player_stats')
    op.drop_table('player_stats')
    op.drop_index(op.f('ix_player_snapshots_week'), table_name='player_snapshots')
    op.drop_index(op.f('ix_player_snapshots_season'), table_name='player_snapshots')
    op.drop_index(op.f('ix_player_snapshots_player_id'), table_name='player_snapshots')
    op.drop_index(op.f('ix_player_snapshots_as_of'), table_name='player_snapshots')
    op.drop_table('player_snapshots')
    op.drop_index(op.f('ix_player_simulation_results_simulation_run_id'), table_name='player_simulation_results')
    op.drop_index(op.f('ix_player_simulation_results_player_id'), table_name='player_simulation_results')
    op.drop_table('player_simulation_results')
    op.drop_index(op.f('ix_player_news_player_id'), table_name='player_news')
    op.drop_table('player_news')
    op.drop_index(op.f('ix_player_injuries_player_id'), table_name='player_injuries')
    op.drop_table('player_injuries')
    op.drop_index(op.f('ix_ownership_projections_slate_id'), table_name='ownership_projections')
    op.drop_index(op.f('ix_ownership_projections_player_id'), table_name='ownership_projections')
    op.drop_table('ownership_projections')
    op.drop_index(op.f('ix_optimization_runs_slate_id'), table_name='optimization_runs')
    op.drop_table('optimization_runs')
    op.drop_index(op.f('ix_ensemble_projections_slate_id'), table_name='ensemble_projections')
    op.drop_index(op.f('ix_ensemble_projections_player_id'), table_name='ensemble_projections')
    op.drop_table('ensemble_projections')
    op.drop_index(op.f('ix_draftkings_players_slate_id'), table_name='draftkings_players')
    op.drop_index(op.f('ix_draftkings_players_player_id'), table_name='draftkings_players')
    op.drop_index(op.f('ix_draftkings_players_dk_player_id'), table_name='draftkings_players')
    op.drop_table('draftkings_players')
    op.drop_index(op.f('ix_correlations_slate_id'), table_name='correlations')
    op.drop_index(op.f('ix_correlations_player_b_id'), table_name='correlations')
    op.drop_index(op.f('ix_correlations_player_a_id'), table_name='correlations')
    op.drop_table('correlations')
    op.drop_index(op.f('ix_betting_lines_game_id'), table_name='betting_lines')
    op.drop_table('betting_lines')
    op.drop_index(op.f('ix_simulations_slate_id'), table_name='simulations')
    op.drop_table('simulations')
    op.drop_index(op.f('ix_players_team_id'), table_name='players')
    op.drop_index(op.f('ix_players_sport'), table_name='players')
    op.drop_index(op.f('ix_players_position'), table_name='players')
    op.drop_index(op.f('ix_players_normalized_name'), table_name='players')
    op.drop_index(op.f('ix_players_full_name'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_games_week'), table_name='games')
    op.drop_index(op.f('ix_games_sport'), table_name='games')
    op.drop_index(op.f('ix_games_season'), table_name='games')
    op.drop_index(op.f('ix_games_kickoff_utc'), table_name='games')
    op.drop_index(op.f('ix_games_home_team_id'), table_name='games')
    op.drop_index(op.f('ix_games_away_team_id'), table_name='games')
    op.drop_table('games')
    op.drop_index(op.f('ix_contests_slate_id'), table_name='contests')
    op.drop_index(op.f('ix_contests_dk_contest_id'), table_name='contests')
    op.drop_table('contests')
    op.drop_index(op.f('ix_teams_sport'), table_name='teams')
    op.drop_index(op.f('ix_teams_abbreviation'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_slates_sport'), table_name='slates')
    op.drop_index(op.f('ix_slates_dk_draft_group_id'), table_name='slates')
    op.drop_table('slates')
    op.drop_table('projection_sources')
    op.drop_index(op.f('ix_model_versions_sport'), table_name='model_versions')
    op.drop_table('model_versions')
    # ### end Alembic commands ###
