"""resolution engine: nullable optimization_run_id, retro_optimal_run_id

Revision ID: ba409e076316
Revises: dd9ffa584191
Create Date: 2026-09-14 18:23:00.932101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba409e076316'
down_revision: Union[str, None] = 'dd9ffa584191'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slate_resolutions', sa.Column('retro_optimal_run_id', sa.String(length=36), nullable=True))
    op.alter_column('slate_resolutions', 'optimization_run_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('slate_resolutions', 'our_best_actual_points',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.create_foreign_key(None, 'slate_resolutions', 'optimization_runs', ['retro_optimal_run_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'slate_resolutions', type_='foreignkey')
    op.alter_column('slate_resolutions', 'our_best_actual_points',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('slate_resolutions', 'optimization_run_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_column('slate_resolutions', 'retro_optimal_run_id')
    # ### end Alembic commands ###
